// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityProv.Data.Migrations.CityProv
{
    [DbContext(typeof(CityProvContext))]
    partial class CityProvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityProv.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            CityId = 10,
                            CityName = "Vancouver",
                            MyProvince = "British Columbia",
                            Population = 500000
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Victoria",
                            MyProvince = "British Columbia",
                            Population = 200000
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "Kelowna",
                            MyProvince = "British Columbia",
                            Population = 100000
                        },
                        new
                        {
                            CityId = 21,
                            CityName = "Toronto",
                            MyProvince = "Ontario",
                            Population = 800000
                        },
                        new
                        {
                            CityId = 22,
                            CityName = "Waterloo",
                            MyProvince = "Ontario",
                            Population = 100000
                        },
                        new
                        {
                            CityId = 23,
                            CityName = "Kingston",
                            MyProvince = "Ontario",
                            Population = 200000
                        },
                        new
                        {
                            CityId = 31,
                            CityName = "Calgary",
                            MyProvince = "Alberta",
                            Population = 400000
                        },
                        new
                        {
                            CityId = 32,
                            CityName = "Edmonton",
                            MyProvince = "Alberta",
                            Population = 400000
                        },
                        new
                        {
                            CityId = 33,
                            CityName = "Lethbridge",
                            MyProvince = "Alberta",
                            Population = 100000
                        });
                });

            modelBuilder.Entity("CityProv.Models.Province", b =>
                {
                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceCode");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            ProvinceCode = "1",
                            ProvinceName = "British Columbia"
                        },
                        new
                        {
                            ProvinceCode = "2",
                            ProvinceName = "Ontario"
                        },
                        new
                        {
                            ProvinceCode = "3",
                            ProvinceName = "Alberta"
                        });
                });

            modelBuilder.Entity("CityProv.Models.City", b =>
                {
                    b.HasOne("CityProv.Models.Province", null)
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode");
                });
#pragma warning restore 612, 618
        }
    }
}
